name: h1c-idr3
channels:
  - conda-forge
dependencies:
  - aipy
  - astropy
  - astropy-healpix
  - cartopy
  - gitpython
  - ipython
  - jax
  - jinja2
  - matplotlib
  - multiprocess
  - numpy
  - pandas
  - pip
  - python
  - pyuvdata
  - rich
  - scipy=1.13
  - scikit-learn
  - six
  - pip:
    - hera-pspec
    - git+https://github.com/nkern/simpleQE
